# Generated by Django 4.2.5 on 2023-09-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tasks',
            field=models.ManyToManyField(related_name='student_tasks', to='school_project.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tasks', to='school_project.student'),
        ),
    ]
