# Generated by Django 4.2.5 on 2023-09-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_project', '0002_student_tasks_alter_task_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tasks',
        ),
    ]
